apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reader-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: reader
    spec:
      containers:
      - name: reader-inst
        image: 192.168.99.100:5000/reader-app
        env:
        - name: BUS_RABBIT
          value: rabbitmq-service
        - name: AUTH_KEYSTONE
          value: keystone-service
        - name: DB_REDIS
          value: redis-service