apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: restapi-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: restapi
    spec:
      containers:
      - name: restapi-inst
        image: 192.168.99.100:5000/flask-app
        ports:
        - containerPort: 5000
        env:
        - name: BUS_RABBIT
          value: rabbitmq-service
        - name: AUTH_KEYSTONE
          value: keystone-service
---
apiVersion: v1
kind: Service
metadata:
  name: restapi-service
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: restapi
  type: NodePort
