apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker-inst
        image: 192.168.99.100:5000/worker-app
        env:
        - name: BUS_RABBIT
          value: rabbitmq-service
        - name: AUTH_KEYSTONE
          value: keystone-service

